### ISSUE TITLE
babel-plugin-glslify

### ISSUE THREAD

**Issue by jamiebuilds** [stackgl/babel-plugin-glslify#1]
Hi! I just wanted to quickly suggest that you switch the name from `glslify-babel` to `babel-plugin-glslify` as this follows the naming scheme of the Babel ecosystem which is encoded into how plugins are loaded:

``` diff
  // ... in your package.json
  "browserify": {
    "transform": [[
      "babelify", {
        "presets": ["es2015"],
-       "plugins": ["glslify-babel"]
+       "plugins": ["glslify"] // maps to babel-plugin-glslify
      }
    ]]
  }
```

**Comment by mikolalysenko** [comment]
Thanks for the advice, I changed the name to follow the babel conventions more closely.
