### ISSUE TITLE
Output shader code includes the current working directory 

### ISSUE THREAD

**Issue by ataber** [stackgl/babel-plugin-glslify#5]
When I use the template tagging with `glsl`, the output string has as its first line the current working directory babel is running in. Is this expected behavior?

I'm using webpack with babel-loader, and I put `glslify` in the plugins array in my `.babelrc`

EDIT: just realized there's an open PR that looks like it's related to this, feel free to close this issue if it's redundant

**Comment by mikolalysenko** [comment]
Solved
